name: Android Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # Hum purana OS use karenge taake compatibility issues na hon
    runs-on: ubuntu-20.04
    env:
      ANDROID_NDK_HOME: ""
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Grant execute permission
      run: chmod +x VirtualApp/gradlew

    - name: Clean Build
      # --stacktrace lagane se agar error aaya, toh wo saaf batayega
      run: cd VirtualApp && ./gradlew clean assembleDebug --stacktrace
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: DevicePro-APK
        path: VirtualApp/app/build/outputs/apk/debug/app-debug.apk
